### ISSUE TITLE
Resin - nodejs & serialport.js

### ISSUE THREAD

**Issue by elaval** [resin-io/basic-resin-node-project#2]
Sorry to open an issue not directly related to this project (but have not found were to ask/report this and I would appreciate a hint)

When trying to work with an usb serialport using serialport.js, (actually I am trying to connect the container to an arduino using johnny-five.js), there are problems accessing the serial ports.

The container has access to the hosts serial ports:  /dev/ttyACM0 and/or /dev/ttyACM1, but it does not have access to /dev/serial/by-path nor /dev/serial/by-id which seems to be used by serialport.js to identify the list of available serial ports (and some node libraries that use serialport.js do not work correctly).

Could this issue be related to the way resin software launches containers and shares /dev/*  between host & container?

Any suggestion on where/who could I ask about this?

**Comment by Page-** [comment]
Hey, just to let you know we are looking into this.  The standard way to contact us would be via the `?` bubble on the bottom right of the site (if it doesn't show up it may be due to aggressive adblocking - we don't show any ads though if you want to disable it for just resin.io).  I'll get back to you here when we have a solution :)

**Comment by Page-** [comment]
Ok, so the answer seems to be to trigger udev in your project, eg change your package.json `"start": "node hello.js"` to `"start": "udevadm trigger && node hello.js"`
